### ISSUE TITLE
AttributeError: type object 'Container' has no attribute 'create_stock_solution'

### ISSUE THREAD

**Issue by Arnab-Debnath01** [ekwan/PyPlate#10]
After running the code for Examply.py or Test_Example.py, I am receiving the error: 

> AttributeError: type object 'Container' has no attribute 'create_stock_solution'. Did you mean: 'create_solution'?

Please find the full error logs given below:
```
Traceback (most recent call last):
  File "C:\Users\907261\PycharmProjects\demoProject2\PyPlate-main\PyPlate-main\examples\Test_Example.py", line 11, in <module>
    triethylamine_5mM = Container.create_stock_solution(triethylamine, 0.005, water, '10 mL')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Container' has no attribute 'create_stock_solution'. Did you mean: 'create_solution'?


```
Please guide me if I am doing anything wrong

**Comment by ekwan** [comment]
This probably has to do with recent API changes (not your fault).  Does this problem occur in the working branch?

**Comment by JMarvi3** [comment]
We changed the API to use `Container.create_solution()`. The syntax, with examples, is [here](https://pyplate-hte.readthedocs.io/en/latest/users_guide/working_with_containers.html). I have also updated `Example.py`.
