### ISSUE TITLE
create_solution is missing documentation

### ISSUE THREAD

**Issue by ekwan** [ekwan/PyPlate#14]
missing docstrings and missing in user guide

**Comment by jlw387** [comment]
Closing this issue, as it seems to have been resolved. 

Here is the current docstring for `create_solution()`: https://github.com/ekwan/PyPlate/blob/29a5aaa5e9e271eff75c1ea0e4589ffb02a44d5e/pyplate/pyplate.py#L1035-L1059

Here is the current ReadTheDocs User Guide page on creating solutions:
https://pyplate-hte.readthedocs.io/en/latest/users_guide/working_with_containers.html#creating-solutions
