### ISSUE TITLE
Recipe.create_solution does not accept list of solute but parameter type and docstring states otherwise

### ISSUE THREAD

**Issue by jonnycoder1** [ekwan/PyPlate#20]
The Recipe's create_solution parameter type and docstring accepts a list of solutes, but it will throw an exception if attempting to pass in a list of solutes:
https://github.com/ekwan/PyPlate/blob/main/pyplate/pyplate.py#L1956
https://github.com/ekwan/PyPlate/blob/main/pyplate/pyplate.py#L1982-L1983

The code for accepting list of solutes is also found under the Container class and it works as expected.
https://github.com/ekwan/PyPlate/blob/main/pyplate/pyplate.py#L1066-L1069

**Comment by JMarvi3** [comment]
Thank you for pointing this out. It should be fixed now. A new version is uploaded to https://pypi.org/project/pyplate-hte/0.4.7/

**Comment by jlw387** [comment]
Closing this issue as it has been resolved.
